const donors = [
  {
    id: 1,
    name: "Aarav Patil",
    bloodGroup: "O+",
    city: "Pune",
    area: "Hinjewadi",
    available: true,
  },
  {
    id: 2,
    name: "Riya Sharma",
    bloodGroup: "O-",
    city: "Pune",
    area: "Baner",
    available: true,
  },
  {
    id: 3,
    name: "Neha Joshi",
    bloodGroup: "A+",
    city: "Pune",
    area: "Kharadi",
    available: true,
  },
  {
    id: 4,
    name: "Vikram Desai",
    bloodGroup: "B+",
    city: "Mumbai",
    area: "Andheri",
    available: true,
  },
  {
    id: 5,
    name: "Kunal More",
    bloodGroup: "O+",
    city: "Pune",
    area: "Wakad",
    available: false,
  },
  {
    id: 6,
    name: "Ananya Kulkarni",
    bloodGroup: "AB+",
    city: "Pune",
    area: "Viman Nagar",
    available: true,
  },
  {
    id: 7,
    name: "Rohan Jadhav",
    bloodGroup: "B-",
    city: "Pune",
    area: "Talawade",
    available: true,
  },
  {
    id: 8,
    name: "Priya Shinde",
    bloodGroup: "A-",
    city: "Pune",
    area: "Balewadi",
    available: true,
  },
  {
    id: 9,
    name: "Aditya Pawar",
    bloodGroup: "O+",
    city: "Pune",
    area: "Bhosari",
    available: true,
  },
  {
    id: 10,
    name: "Sneha Gaikwad",
    bloodGroup: "A+",
    city: "Pune",
    area: "Shivajinagar",
    available: true,
  },
  {
    id: 11,
    name: "Manav Chavan",
    bloodGroup: "B+",
    city: "Pune",
    area: "Aundh",
    available: false,
  },
  {
    id: 12,
    name: "Isha Bhosale",
    bloodGroup: "O-",
    city: "Pune",
    area: "Kothrud",
    available: true,
  },
  {
    id: 13,
    name: "Omkar Sawant",
    bloodGroup: "AB-",
    city: "Pune",
    area: "Pimpri",
    available: true,
  },
  {
    id: 14,
    name: "Kavya More",
    bloodGroup: "A+",
    city: "Pune",
    area: "Chinchwad",
    available: true,
  },
  {
    id: 15,
    name: "Sahil Patil",
    bloodGroup: "B+",
    city: "Pune",
    area: "Nigdi",
    available: true,
  },
  {
    id: 16,
    name: "Meera Deshmukh",
    bloodGroup: "O+",
    city: "Pune",
    area: "Hadapsar",
    available: true,
  },
  {
    id: 17,
    name: "Yash Thakur",
    bloodGroup: "A-",
    city: "Pune",
    area: "Magarpatta",
    available: true,
  },
  {
    id: 18,
    name: "Pooja Pawar",
    bloodGroup: "AB+",
    city: "Pune",
    area: "Koregaon Park",
    available: false,
  },
  {
    id: 19,
    name: "Rahul Kadam",
    bloodGroup: "O+",
    city: "Pune",
    area: "Yerawada",
    available: true,
  },
  {
    id: 20,
    name: "Tanvi Joshi",
    bloodGroup: "B-",
    city: "Pune",
    area: "Camp",
    available: true,
  },
  {
    id: 21,
    name: "Siddhant More",
    bloodGroup: "A+",
    city: "Pune",
    area: "Pashan",
    available: true,
  },
  {
    id: 22,
    name: "Mitali Shukla",
    bloodGroup: "O-",
    city: "Pune",
    area: "Sus",
    available: true,
  },
  {
    id: 23,
    name: "Harsh Vaidya",
    bloodGroup: "B+",
    city: "Pune",
    area: "Ravet",
    available: true,
  },
  {
    id: 24,
    name: "Nikita Salunkhe",
    bloodGroup: "AB+",
    city: "Pune",
    area: "Dhanori",
    available: true,
  },
  {
    id: 25,
    name: "Akash Wagh",
    bloodGroup: "O+",
    city: "Pune",
    area: "Lohegaon",
    available: true,
  },
  {
    id: 26,
    name: "Sakshi Naik",
    bloodGroup: "A+",
    city: "Pune",
    area: "Vishrantwadi",
    available: true,
  },
  {
    id: 27,
    name: "Nikhil Mane",
    bloodGroup: "B+",
    city: "Pune",
    area: "Moshi",
    available: false,
  },
  {
    id: 28,
    name: "Vaishnavi Kale",
    bloodGroup: "O-",
    city: "Pune",
    area: "Wagholi",
    available: true,
  },
];

export default donors;